# add your custom package feeds here
#
# src/gz example_feed_name http://www.example.com/path/to/files
src/gz openwrt_core https://mirrors.tencent.com/lede/snapshots/targets/x86/64/packages
# src/gz openwrt_base https://mirrors.tencent.com/lede/snapshots/packages/x86_64/base
src/gz openwrt_base https://mirrors.pku.edu.cn/immortalwrt/releases/23.05.3/packages/x86_64/base
# src/gz openwrt_gecoosac https://mirrors.tencent.com/lede/snapshots/packages/x86_64/gecoosac
# src/gz openwrt_luci https://mirrors.tencent.com/lede/releases/18.06.9/packages/x86_64/luci
src/gz openwrt_luci https://mirrors.pku.edu.cn/immortalwrt/releases/23.05.3/packages/x86_64/luci
# src/gz openwrt_packages https://mirrors.tencent.com/lede/snapshots/packages/x86_64/packages
src/gz openwrt_packages https://mirrors.pku.edu.cn/immortalwrt/releases/23.05.3/packages/x86_64/packages
# src/gz openwrt_routing https://mirrors.tencent.com/lede/snapshots/packages/x86_64/routing
src/gz openwrt_routing https://mirrors.pku.edu.cn/immortalwrt/releases/23.05.3/packages/x86_64/routing
# src/gz openwrt_small https://mirrors.tencent.com/lede/snapshots/packages/x86_64/small
# src/gz openwrt_smallpackage https://mirrors.tencent.com/lede/snapshots/packages/x86_64/smallpackage
# src/gz openwrt_telephony https://mirrors.tencent.com/lede/snapshots/packages/x86_64/telephony
src/gz openwrt_telephony https://mirrors.pku.edu.cn/immortalwrt/releases/23.05.3/packages/x86_64/telephony
